# Generated by Django 2.0.8 on 2018-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigdata', '0002_auto_20180921_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PigHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigname', models.CharField(max_length=20)),
                ('health_status', models.CharField(max_length=30)),
            ],
        ),
    ]
